fixed syntax for gcloud builds cmd. (#1208)
Fixed syntax of gcloud cmd to build container.
was:
gcloud build submit --tag gcr.io/[YOUR_PROJECT_ID]/cra-cloud-run
changed to:
gcloud builds submit --tag gcr.io/[YOUR_PROJECT_ID]/cra-cloud-run

As reported by gcloud:
ERROR: (gcloud) Invalid choice: 'build'.
Maybe you meant:
  gcloud builds submit