Npm build issues fix (#821)
* npm build issue fix

I was getting following error while trying to do npm install:
'''
node_modules/@types/lodash/common/object.d.ts(1689,12): error TS2304: Cannot find name 'Exclude'.

1689         ): Exclude<TObject[TKey], undefined> | TDefault;
'''
By upgrade to 2.8.3 for TypeScript fixed issue

* fix npm build issue

was getting:
when running npm install
```
src/index.ts:24:10 - error TS2724: Module '"vm"' has no exported member 'runInDebugContext'. Did you mean 'runInNewContext'?

24 import { runInDebugContext } from 'vm';
            ~~~~~~~~~~~~~~~~~
```