Fixes to make example work with Terraform v0.12.21 (#1172)
* terraform fmt

* Fix access_config on network_interface

Before:

```
$ terraform validate

Error: Unsupported argument

  on compute.tf line 31, in resource "google_compute_instance" "default":
  31:     access_config = {}

An argument named "access_config" is not expected here. Did you mean to define
a block of type "access_config"?
```

After:

```
$ terraform validate
Success! The configuration is valid.
```

While at it, also apply `terraform fmt` on the file.

* Set project for data.google_compute_zones

Before:

```
$ terraform plan -no-color
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.google_compute_zones.available: Refreshing state...

Error: project: required field is not set

  on compute.tf line 15, in data "google_compute_zones" "available":
  15: data "google_compute_zones" "available" {}
```

After: `terraform plan` succeeds.

* Update Terraform versions, after recent changes

* Fix note about referencing project ID

Update note about referencing project ID
from `google_project_service` resource in
`google_compute_instance` resource.

I'm not sure is this optimal solution. This doesn't
introduce race as there is only one instance of
`google_project_service.service`, but if there
would be more instances, then not sure how Terraform
will handle activation of APIs, from parallelism
point of view and race issue discussed in the note.

* Explicitly reference needed `google_project_service` instance

If the set of services to enable via `google_project_service` grows,
then first element doesn't need to be with `compute.googleapis.com`
instance. Be explicit and reference correct instance.

* Explicitly depends on `google_project_service.service` resource

Make it simple and use explicit dependency on resource which
enables APIs. I think this is more clear.

* sync code in index.md with project.tf and compute.tf files